services:
  db:
    container_name: elia-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: elia-api
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV_STATE=${ENV_STATE}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT} 
      - DB_SSL=${DB_SSL} 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_started
    volumes:
      - .:/app

volumes:
  postgres_data:
