services:
  db:
    container_name: elia-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: elia-api
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV_STATE=global
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT} 
      - DB_SSL=${DB_SSL} 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BIGQUERY_JSON_KEY_B64=${BIGQUERY_JSON_KEY_B64}
      - GOOGLE_LLM_MODEL=${GOOGLE_LLM_MODEL}
      - CHAT_HISTORY_LIMIT=${CHAT_HISTORY_LIMIT}
      - GEOFLIP_API_KEY=${GEOFLIP_API_KEY}
      - GEOFLIP_API_URL=${GEOFLIP_API_URL}
    depends_on:
      db:
        condition: service_started
    volumes:
      - .:/app

volumes:
  postgres_data:
